# Grill-Scrible
A blogging website
= The GrillScrible: 
:toc:
:toc-placement!:

**The Grill Scrible** is a powerful and flexible backend **Backend** for a **Blogging Website**. Built using **Django Rest Framework**,  it provides all the essential functionalities required to create and manage a dynamic blogging platform. With features like user authentication, tagging, and commenting system, The **Grill Scrible** is designed to empower bloggers and enhance the user experience.

The project is currently hosted on __PythonAnyWhere__ server for testing purpose : http://pranavtiwari.pythonanywhere.com/

== Website 

[discrete]
# INDEX

toc::[]

== Endpoints



=== Blog posts
====

.Blog posts end points
[width="80%",cols="3,^2,^2,10",options="header"]
|=========================================================
Purpose |Endpoints |Method |Sample| Authentication

View all blog posts |'blog/list/' | **GET** | http://pranavtiwari.pythonanywhere.com/blog/list/ |[Authentication: none]

|22-Aug-08 |23:03 | 152 |
Back-to-back with previous interval.

|24-Aug-08 |40:00 | 145 |
Moderately hard interspersed with 3x 3min intervals (2min
hard + 1min really hard taking the HR up to 160).

|=========================================================

End point **:** 'blog/list/'           

Method: **GET** [Authentication: none]
 
__sample__ **:** http://pranavtiwari.pythonanywhere.com/blog/list/

==== Create a blog post
End point **:** 'blog/list/'           

Method: **POST** [Authentication: required]

__sample__ **:** http://pranavtiwari.pythonanywhere.com/blog/list/

==== View an individual blog post

End point **:** 'blog/<int:blog-id>/'           

Method: **GET** [Authentication: none]
 
__sample__ **:** http://pranavtiwari.pythonanywhere.com/blog/1/ [for blog 1]

==== Update a individual blog post

End point **:** 'blog/<int:blog-id>/'

Method: **PUT** [Authentication: IsAuthor]

==== View all blog posts of logged in user
End point **:** 'blog/mylist/'           

Method: **GET** [Authentication: required]
 
__sample__ **:** http://pranavtiwari.pythonanywhere.com/blog/mylist/

=== Blog posts

==== View all blog posts
End point **:** 'blog/list/'           

Method: **GET** [Authentication: none]
 
__sample__ **:** http://pranavtiwari.pythonanywhere.com/blog/list/

==== Create a blog post
End point **:** 'blog/list/'           

Method: **POST** [Authentication: required]

__sample__ **:** http://pranavtiwari.pythonanywhere.com/blog/list/

==== View an individual blog post

End point **:** 'blog/<int:blog-id>/'           

Method: **GET** [Authentication: none]
 
__sample__ **:** http://pranavtiwari.pythonanywhere.com/blog/1/ [for blog 1]

==== Update a individual blog post

End point **:** 'blog/<int:blog-id>/'

Method: **PUT** [Authentication: IsAuthor]


== Features 
**The Backend** contain all essential features:

=== User Authentication 	
The Grill Scrible enables user registration, login, and logout functionality, ensuring secure access to the platform through **JWT Authorization**.

==== Unauthorized Access
- Can access all blogs and their associated comments
- Can can like any blog
- Can comment on any blog

==== Authorization
- To write blog you must be authenticated 
- Only the author can updaqte his blog
- User can view all his details and blogs from profile page and can edit them

=== Searching
Implement a powerful search feature that allows users to search for specific blog posts using author details, keywords or tags.

=== Tagging System 	
Organize blog posts with tags to improve categorization and discoverability. 
__only admin can create and modify tags__


***Demo***


***Demo***

***__Anonymous User Logged-In__***



***_Admin Logged-In_***





