# Generated by Django 4.2.3 on 2023-07-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
