# Generated by Django 4.2.3 on 2023-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='related_blogs', to='blogs.tag'),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_count',
            field=models.ManyToManyField(blank=True, related_name='blog_like_count', to='blogs.ipmodel'),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_ip',
            field=models.ManyToManyField(blank=True, related_name='blog_like_detail', to='blogs.ipmodel'),
        ),
    ]
