# Generated by Django 4.2.3 on 2023-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_ipmodel_remove_blog_likes_alter_blog_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
