# Generated by Django 4.2.3 on 2023-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_blog_likes_count_blog_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes_ip',
            field=models.ManyToManyField(blank=True, related_name='blog_like_ip', to='blogs.ipmodel'),
        ),
    ]
