# Generated by Django 4.2.3 on 2023-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profile/default_avatar.jpg', upload_to='profile', verbose_name='Photo'),
        ),
    ]
