# Generated by Django 4.2.3 on 2023-07-20 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('accounts', '0005_profile_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('out_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='token_blacklist.outstandingtoken')),
            ],
        ),
    ]
